# Generated by Django 5.0.2 on 2024-04-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('imdb_rating', models.FloatField()),
                ('genre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(verbose_name=('Male', 'Female'))),
                ('related', models.ManyToManyField(blank=True, related_name='netflix_actors', to='movie.movie')),
            ],
        ),
    ]
