# Generated by Django 5.0.2 on 2024-04-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='related',
        ),
        migrations.AddField(
            model_name='movie',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='netflix_actors', to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6),
        ),
    ]
